spring:
  application:
    name: client-consumer
  datasource:
    url: jdbc:mysql://localhost:3306/jfmf?serverTimezone=GMT%2b8
    password: "123456"
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-wait: 20000 #连接池最大阻塞时间，负数代表无限制
        max-active: 20  #最大连接数
    timeout: 3000 #连接超时
#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
#    username: system
#    password: 123456

spring.:
  second:
   datasource:
     url: jdbc:oracle://192.168.100.202:1521/orcl
     password: "isc"
     username: isc
     driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    show-sql: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: a0cc5bc5-7778-44d3-84e9-39af6ec721b9

server:
  port: 1001

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  #type-aliases-package: clientconsumer.clientconsumer.consumer.**
  configuration:
          log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

